---
- name: Install dev tools
  yum:
    name:
      - git
      - gdb
      - gcc
      - python
      - perl
      - automake
      - autoconf
      - libtool
      - flex
      - bison
    state: present
